---
- name: Install Web Server
  hosts: webserver
  vars:
    web_pkg: httpd
    firewalld_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    python_pkg: wget
    rule: http
  become: true
  tasks:

    - name: Lates Version of httpd snd firewall installed
      ansible.builtin.dnf:
        name:
          - "{{ web_pkg }}"
          - "{{ firewalld_pkg }}"
        state: present

    - name: Ensure enabled and running "{{ web_service }}" 
      ansible.builtin.service:
        name: "{{ web_service }}"
        state: started
        enabled: yes

    - name: Ensure enabled and running "{{ firewall_service }}" 
      ansible.builtin.service:
        name: "{{ firewall_service }}"
        state: started
        enabled: yes

    - name: test html page installed 
      ansible.builtin.copy:
        content: "Example web Content"
        dest: /var/www/html/index.html

    - name: Permit traffic in zone for "{{ web_service }}" service 
      ansible.posix.firewalld:
        service: "{{ rule  }}"
        permanent: true
        state: enabled
        immediate: true 


- name: Test Web Server
  hosts: localhost
  tasks:

   - name: Test Web Server
     ansible.builtin.uri:
      url: http://vm-2-node2-ansible.example.com
      status_code: 200


