---
- name: Enable intranet Services
  hosts: intranet
  become: yes
  tasks:
    - name: Latest version of httpd and firewall installed
      ansible.builtin.yum:
       name:
        - httpd
        - firewalld
       state: latest

    - name: Firewall enabled and running
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

    - name: Firewall permits http service
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: httpd enabled and running 
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: test html page installed
      ansible.builtin.copy:
        content: "Welcome to the example.com intranet\n"
        dest: /var/www/html/index.html


- name: Test web server
  hosts: localhost
  tasks:

    - name: connect to intranet web server 
      ansible.builtin.uri:
        url: http://vm-2-node2-ansible.example.com
        status_code: 200

