---
- name: Add text to an existing file
  hosts: servers
  become: false
  tasks:

    - name: Add a single line of thext to a file 
      ansible.builtin.lineinfile:
        path: /home/automation/users.txt
        line: "This line was added by the linie in file module"
        state: present

